services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    labels:
      glance.name: Watchtower
      glance.icon: di:watchtower
      glance.description: automatic docker container updates
      glance.category: management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup --rolling-restart --include-restarting
    networks:
      - net

  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    labels:
      glance.name: cadvisor
      glance.icon: di:cadvisor
      glance.description: docker container stat tracking application
      glance.category: management
    privileged: true
    ports:
      - "8228:8080"
    command:
      - --docker_only=true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - net

  windows-exporter:
    image: ghcr.io/prometheus-community/windows-exporter:latest
    container_name: windows-exporter
    restart: unless-stopped
    labels:
      glance.name: Windows Exporter
      glance.icon: si:prometheus
      glance.description: windows system metrics for prometheus
      glance.category: management
    ports:
      - "9182:9182"
    networks:
      - net